### ISSUE TITLE
关于连线类游戏的一点优化建议

### ISSUE THREAD

**Issue by KID1412999** [ZhiqingXiao/boardgame2#1]
肖老师你好，我用了你的代码测试的时候发现连线类游戏判断输赢的时候你采用的是每次更新局面后都扫描全局，我这边的一点优化想法就是，对于连线类游戏判断胜负每次局面变化时只需要扫描新加入的这个点的辐射出来的四条线，看是不是有k个连成一线，这样的话，在判断胜负这一块就省很多时间。

**Comment by ZhiqingXiao** [comment]
有道理！谢谢您的建议。
